package com.example.demo.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
@Entity
@Table(name = "deal")
public class Deal {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "deal_unique_id")
  private long id; // SERIAL PRIMARY KEY

  // timestamp should be generated by the database
  @Column(
    name = "deal_timestamp",
    columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
  )
  private String timestamp; // TIMESTAMP

  // fields
  @NotBlank(message = "from currency iso code must not be blank")
  @Column(name = "from_currency_iso_code")
  private String fromCurrencyIsoCode; // VARCHAR(3)

  @NotBlank(message = "to currency iso code must not be blank")
  @Column(name = "to_currency_iso_code")
  private String toCurrencyIsoCode; // VARCHAR(3)

  @NotNull(message = "deal amount must not be null")
  @Min(value = 1, message = "to currency iso code must be 3 characters")
  @Column(name = "deal_amount")
  private long dealAmount; // FLOAT
}
